### PR TITLE
Added "init_instance" event and fake "disabled" prop

### PR DESCRIPTION
**Pull request by grantmooney**

### CODE REVIEW

**Comment by theroozbeh** [comment]
Thank you for this. but we should include all of callbacks

**Comment by grantmooney** [comment]
The "init_instance_callback" contains critical input synchronization functionality and should not be able to be overwritten. Instead it should be extended via a component event. Try adding "init_instance_callback() {}" to your other options and you will see what I mean.

If this is not included I am forced to use my fork or another library, as this is a application-breaking bug.

**Comment by grantmooney** [comment]
Why did you close this and still use my initialization callback pattern?

**Comment by theroozbeh** [comment]
I really appreciated your contribution. 
Yes, my pattern is like yours, but your code needed some improvements. So I decided to rewrite it myself.

**Pull request closed without merging**
